### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by jahaddow** [cannonbeach/opensrthub#10]
Hi, I tried installing your software on an Oracle ARM64 instance running Debian 12 but had failures. Is this supported?

**Comment by cannonbeach** [comment]
I have not implemented ARM64 support.  What were the failures you had?  I don't really have any immediate plans to support ARM64 since I don't have access to that specific hardware.  Would you be willing to sponsor the feature?  Provide hardware?  Cloud credits?
