### ISSUE TITLE
Libsrt ffmpeg version

### ISSUE THREAD

**Issue by ma-blip** [cannonbeach/opensrthub#12]
Any specific reason older libraries are used?

**Comment by cannonbeach** [comment]
I originally had a requirement from a customer to match the libsrt version for compatibility reasons, but you should be able to update libsrt to the latest without any issues if you want (as long as the APIs have not changed).

You can update to the latest libsrt version by changing the line in setupopensrthub.sh from:
git checkout tags/v1.4.4 -b v1.4.4
to
git checkout tags/v1.5.3 -b v1.5.3

This is something I will likely revisit or provide a way to have multiple docker containers with different versions.  If you have an immediate need to update, you're more than welcome to fork the repository.
