### ISSUE TITLE
  udp output

### ISSUE THREAD

**Issue by paherrera** [cannonbeach/opensrthub#13]
![Sin título](https://github.com/cannonbeach/opensrthub/assets/31813526/54f726bd-7a4a-43fe-89b2-28bd1356c4a5)
I have to create a udp server or something similar to then reproduce it. Can the srt be retransmitted with the server's IP?

**Comment by cannonbeach** [comment]
What are you trying to do?

SRT to UDP
Or
UDP to SRT

**Comment by cannonbeach** [comment]
That field is the destination address.  If you want to send it to the same system, you can set it to loopback: 127.0.0.1 or you can send it to another system.

**Comment by skysatel** [comment]
Hi.

After configuring my server to receive an SRT and Broadcast a UDP Multicast, I am not getting Multicast output on the second NETWORK adapter. The server announces SRT is Correct UDP Output is correct but VLC or TS_Reader does not see the layer 2 traffic Multicas, Thank you

**Comment by cannonbeach** [comment]
1) Make sure the multicast route is present (please post your route table here)
route -n
You should see an entry similar to the following:
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
224.0.0.0        0.0.0.0           240.0.0.0          U       0         0        0     eth4
If it is not present, please add it as follows:
**sudo route add -net 224.0.0.0 netmask 240.0.0.0 dev eth4**
(where eth4 should be your interface)

2) Check that you see traffic on the interface using tcpdump
sudo tcpdump dst MULTICASTIP and port MULTICASTPORT
where MULTICASTIP is your destination multicast address and MULTICASTPORT is your destination multicast port

**Comment by skysatel** [comment]
Hi cannonbeach, Thanks for your help, I now have UDP Multicast Traffic output through the second network adapter.
