### ISSUE TITLE
User and password security for the opensrthub administration Web interface

### ISSUE THREAD

**Issue by skysatel** [cannonbeach/opensrthub#14]
Hello Sir, within your project you have planned to implement some security validation on the server.
Once it is connected to the Internet with a Public IP, it is exposed to the security of the configuration parameters.

Thanks for your reply.

Regards,

Skysatel

**Comment by cannonbeach** [comment]
I have no immediate plans to include this feature. You can either add this on your own or email me if you want to sponsor adding this feature.
