### ISSUE TITLE
Listener from outside not working.

### ISSUE THREAD

**Issue by TagorePde** [cannonbeach/opensrthub#15]
Hi
i tested the caller mode, working perfect.
Now i want to test the listener mode, i can only get working from the same pc, but not from the lan.
Where are the logs? how can debug this?

IPTABLES empty:
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

![image](https://github.com/user-attachments/assets/91c6fa3c-2435-42d6-989d-62c0069dc150)

Line used for sending the srt from the lan pc next to the server, from ip 192.168.31.68:
ffmpeg -f lavfi -i testsrc=duration=3600:size=1920x1080:rate=30 -f mpegts 'srt://192.168.31.67:14003'

getting:
[srt @ 0x5643c7e7fb40] Connection to srt://192.168.31.67:14003 failed: Input/output error
srt://192.168.31.67:14003: Input/output error

i changed the http default web port from 8080 to 8090 editing the server.js file under /var/app ( the 8080 is in use)

Regards.

**Comment by cannonbeach** [comment]
I think your source address needs to be 192.168.31.67 since that is the local address of the server.  If that doesn't work, can you also post your config file here?

**Comment by TagorePde** [comment]
the pc where the opensrthub is installed is in 192.168.31.67 and i want to send the srt from 192.168.31.68.
I still need to add the 67 as the source address? i will test now and if not work, i will post the configs after that and also report back if i get it working. thanks.
Regards.
