### ISSUE TITLE
PM2 Start Status Errored

### ISSUE THREAD

**Issue by stromtroopers03** [cannonbeach/opensrthub#16]
Hi Cannonbeach

I'm having issue while starting using your given command and didn't find any much information on log, could you help me ? 

sorry i'm newbie on this environment
![image](https://github.com/user-attachments/assets/fa9ca985-d61a-4ee6-bf93-3cfe7877ba16)

**Comment by cannonbeach** [comment]
After you execute the setup script (sudo ./setupopensrthub.sh), please navigate in the terminal to the /var/app directory and run the following commands:
/var/app:~$ sudo pm2 start --name 'opensrthub' server.js --wait-ready
/var/app:~$ sudo pm2 save
The instructions are for a system based install, so you can't do this from your home directory.
