### ISSUE TITLE
srt listener source mode hang

### ISSUE THREAD

**Issue by cannonbeach** [cannonbeach/opensrthub#7]

**Comment by cannonbeach** [comment]
SRT source mode Listener hangs up after about 16-18 hours with some streams.  Need to add more debug.

**Comment by skureal** [comment]
How would I set up a source in listener mode?

Is there an general overview of all the possible option for the .json config file?

**Comment by cannonbeach** [comment]
Which scenario are you trying to do?
1. UDP Input to SRT Listener Output (Destination pulls from opensrthub)
2. SRT Listener Input (Source pushes to opensrthub) to UDP Output

**Comment by skureal** [comment]
actually i would like to use it as SRT relay with SRT listener for input and output.
I might need different SRT settings for in / put as well, such as latency or different encryption.

**Comment by skureal** [comment]
ok, that's a workaround, which might work for me.
would I need to create 2 separate json config  files and start 2 instances of opensrthub, each point to a unique config file? or can I have that setup in a single config file?

**Comment by cannonbeach** [comment]
It will require two configurations and two instances of opensrthub.
